@startuml Get_Artworks
actor user
boundary interface
control backend
database db

group freeArtwork
    user -> interface : goes to artworks' list's page
        interface -> backend : get all artworks Request
            backend -> db : get list of artwork
            db -[#green]-> backend : give all the artworks
        backend -[#green]-> interface : forward artworks data
    interface -[#green]-> user : display artworks list
    user -> interface : click on an artwork
        interface -> backend : get one artwork request
            backend -> db : get one artwork info request
            db -[#green]-> backend : give artwork infos
        backend -[#green]-> interface : forward artwork infos
    interface -[#green]-> user : display the artwork infos
end
@enduml