@startuml Valid_an_Artwork
actor user
boundary Front
box "Back End" #LightBlue
control controller
database db
end box

== Add Artwork  ==
user -> Front : fill Artwork form
Front -> controller : submit Artwork form
alt User is connected && is admin
    alt Form is valid
        alt Atwork has status "à modérer"
            controller -> db : Send data to update form
            alt Save data
                controller <[#green]- db : <color #green><b>Data has been saved
                Front <[#green]- controller : <color #green><b>Success : Data has been saved    
            else Fail to save Data
                controller <[#red]- db : <color #red>Fail to save data
                Front <[#red]- controller : <color #red>Fail to save data
            end
        else
            Front <[#red]- controller : <color #red>Artwork has already been moderate
        end
    else Form is not valid
        Front <[#red]- controller  : <color #red>Form is not valid
    end
else User is not connected || is not admin
    Front <[#red]- controller : <color #red>Permission denied
end




@enduml
